spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myusername
    password: mypassword
#когда приложение в отдельном контейнере
    url: jdbc:mysql://host.docker.internal:3306/collective_blog_db
#    url: jdbc:mysql://localhost:3306/collective_blog_db
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  sql:
    init:
      mode: always
      data.sql.sql-locations: data.sql
      schema.sql.sql-locations: schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: mysql
  mvc:
    hiddenmethod:
      filter:
        enabled: true