spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: myusername
    password: mypassword
    url: jdbc:postgresql://localhost:5432/mylibrary
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  sql:
    init:
      mode: always
      data.sql.sql-locations: data.sql
      schema.sql.sql-locations: schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql
  mvc:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    default:
      execution:
        isolation:
          strategy: "SEMAPHORE"