spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: myusername
    password: mypassword
    url: jdbc:postgresql://localhost:5432/mylibrary
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql




#  datasource:
#    url: jdbc:h2:mem:testdb
#    initialization-mode: always

#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    show-sql: true
