# FROM openjdk:11-jre-slim
# COPY /target/homework17-0.0.1-SNAPSHOT.jar /app/app.jar
# EXPOSE 8080
# ENTRYPOINT ["java", "-jar", "/app/app.jar"]


FROM openjdk:11-jre-slim
COPY /target/homework17-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "homework17-0.0.1-SNAPSHOT.jar"]